- name: 1.Create kube-controller-manager service startup file
  template:
    src: "../templates/kube-controller-manager.service-{{k8sver}}.j2"
    dest: /etc/systemd/system/kube-controller-manager.service
- name: 2.Create {{k8s_install_home}}/kubernetes/kube-controller-manager directory
  file: 
    path: "{{k8s_install_home}}/kubernetes/kube-controller-manager"
    state: directory
- name: 3.Start kube-controller-manager service
  systemd:
    daemon_reload: true
    name: kube-controller-manager
    state: restarted
    enabled: true

