- name: 1.Stop kubelet service
  service:
    name: kubelet
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 2.Stop kube-proxy service
  service:
    name: kube-proxy
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 3.Stop runtime service
  service:
    name: containerd
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 4.Umount kubelet disk partition
  shell: "for diskPartition in `mount | grep kubelet | awk '{print $3}'` ; do umount $diskPartition ; done"
  ignore_errors: yes
- name: 5.Delete bin file
  file:
    path: /opt/cni
    state: absent
  ignore_errors: yes
- file:
    path: /etc/cni
    state: absent
  ignore_errors: yes
- file:
    path: /usr/local/bin/{{item}}
    state: absent
  with_items:
    - calicoctl
    - containerd
    - containerd-shim
    - containerd-shim-runc-v1
    - containerd-shim-runc-v2
    - crictl
    - ctr
    - runc
    - kubelet
    - kube-proxy
    - ipvsinit.sh
    - resolvinit.sh
  ignore_errors: yes
- name: 6.Delete kube-proxy service file
  file:
    path: /etc/systemd/system/kube-proxy.service
    state: absent
  ignore_errors: yes
- file:
    path: "{{software_home}}/k8s/kubernetes/kube-proxy"
    state: absent
  ignore_errors: yes
- name: 7.Delete kubelet service file
  file:
    path: /etc/systemd/system/kubelet.service
    state: absent
  ignore_errors: yes
- file:
    path: "{{software_home}}/k8s/kubernetes/kubelet"
    state: absent
  ignore_errors: yes
- name: 8.Delete runtime service file
  file:
    path: /etc/systemd/system/containerd.service
    state: absent
  ignore_errors: yes



