- name: 1.Create cniplugin directory
  file:
    path: "{{k8s_install_home}}/cniplugin/{{item}}"
    state: directory
  with_items:
    - flannel
    - calico
    - kuberouter
    - weave
    - cilium

- name: 2.Create calico.yaml file
  template:
    src: "../templates/calico.yaml.j2"
    dest: "{{k8s_install_home}}/cniplugin/calico/calico.yaml"

- name: 3.Deploy calico
  shell: "/usr/sbin/kubectl --kubeconfig=/etc/kubernetes/ssl/kube-install.kubeconfig apply -f {{k8s_install_home}}/cniplugin/calico/calico.yaml"



